package com.template.project

import android.annotation.SuppressLint
import androidx.appcompat.app.AppCompatActivity
import androidx.navigation.NavController
import androidx.navigation.NavDestination
import androidx.navigation.findNavController
import kotlinx.android.synthetic.main.activity_main.*
import org.androidannotations.annotations.AfterViews
import org.androidannotations.annotations.EActivity

/**
 * Application use the single activity architecture which was noted as recommended from google blog.
 *
 *(search: single-Activity) https://android-developers.googleblog.com/2018/05/use-android-jetpack-to-accelerate-your.html?m=1
 */
@SuppressLint("Registered" /* instead we have registered the enhanced class generated by AndroidAnnotations */)
@EActivity(R.layout.activity_main)
class MainActivity : AppCompatActivity() {

    /**
     * Connect the navigation architecture component and show the configured start fragment.
     */
    override fun onSupportNavigateUp() = findNavController(R.id.nav_host_fragment).navigateUp()

    @AfterViews
    fun setup() {
        setSupportActionBar(toolbar)

        // change title on navigation until there is a proper way of doing that
        // https://issuetracker.google.com/issues/80267266
        findNavController(R.id.nav_host_fragment).addOnNavigatedListener { _, destination ->
            this.title = destination.label
            this.supportActionBar!!.setDisplayHomeAsUpEnabled(false)
        }
    }
}
